services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: expenses
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      retries: 20

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"   # host:container (we use 8081 since 8080 was busy)
    depends_on:
      - db

volumes:
  db_data:
